fix property missing
otherwise webpack crashes with following error:

[handleMissingEntity]
 TypeError: _entities_lib_properties__WEBPACK_IMPORTED_MODULE_5__.propertiesEditorsConfigs[property] is undefined
    entityProperties works_browser_helpers.ts:187
    <anonymous> works_browser_helpers.ts:187
    a main.js:3724
    <anonymous> works_browser_helpers.ts:1
    ts app_modules_entities_components_layouts_entity_list_row_svelte.js:28
    __webpack_require__ main.js:3651
    fn main.js:3999
    <anonymous> entity_list_row.svelte:12
    a main.js:3724
    <anonymous> entity_list_row.svelte:1
    svelte app_modules_entities_components_layouts_entity_list_row_svelte.js:48
    __webpack_require__ main.js:3651
    fn main.js:3999
    <anonymous> deduplicate_homonyms.svelte:17
    a main.js:3724
    <anonymous> deduplicate_homonyms.svelte:1
    svelte app_modules_entities_components_layouts_deduplicate_homonyms_svelte.js:38
    __webpack_require__ main.js:3651
    fn main.js:3999
    <anonymous> work.svelte:28
    a main.js:3724
    <anonymous> work.svelte:1
    svelte app_modules_entities_components_layouts_work_svelte.js:58
    __webpack_require__ main.js:3651
    fn main.js:3999
loggers.ts:57
    error loggers.ts:57
    showOtherError redirect.ts:175
    Backbone 2
    request radio.ts:27
    execute radio.ts:34
    handleMissingEntity entities.ts:351
    showEntity entities.ts:60