Revert "dependencies: update webpack* dependencies"
This reverts commit 1f0d9036ad60daef8643fa0c960e943bffd60658.

Due to difficulties to properly deploy the change on devs machines, for obscure reasons:

Here is the error message obtain after updating on some machines o_O:

client/node_modules/http-proxy-middleware/dist/context-matcher.js:25
        throw new Error(errors_1.ERRORS.ERR_CONTEXT_MATCHER_INVALID_ARRAY);
              ^

Error: [HPM] Invalid context. Expecting something like: ["/api", "/ajax"] or ["/api/**", "!**.html"]
    at Object.match (client/node_modules/http-proxy-middleware/dist/context-matcher.js:25:15)
    at HttpProxyMiddleware.shouldProxy (client/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:77:35)
    at HttpProxyMiddleware.middleware (client/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:19:22)
    at handler (client/node_modules/webpack-dev-server/lib/Server.js:2313:20)
    at Layer.handle [as handle_request] (client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (client/node_modules/express/lib/router/index.js:328:13)
    at client/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (client/node_modules/express/lib/router/index.js:346:12)
    at next (client/node_modules/express/lib/router/index.js:280:10)
    at goNext (client/node_modules/webpack-dev-middleware/dist/middleware.js:135:16)
    at middleware (client/node_modules/webpack-dev-middleware/dist/middleware.js:148:13)
    at Layer.handle [as handle_request] (client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (client/node_modules/express/lib/router/index.js:328:13)
    at client/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (client/node_modules/express/lib/router/index.js:346:12)
    at next (client/node_modules/express/lib/router/index.js:280:10)
    at compression (client/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (client/node_modules/express/lib/router/index.js:328:13)
    at client/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (client/node_modules/express/lib/router/index.js:346:12)
    at next (client/node_modules/express/lib/router/index.js:280:10)
    at middleware (client/node_modules/webpack-dev-server/lib/Server.js:1947:11)
    at Layer.handle [as handle_request] (client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (client/node_modules/express/lib/router/index.js:328:13)
    at client/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (client/node_modules/express/lib/router/index.js:346:12)
    at next (client/node_modules/express/lib/router/index.js:280:10)
    at expressInit (client/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (client/node_modules/express/lib/router/index.js:328:13)
    at client/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (client/node_modules/express/lib/router/index.js:346:12)
    at next (client/node_modules/express/lib/router/index.js:280:10)
    at query (client/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (client/node_modules/express/lib/router/index.js:328:13)
    at client/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (client/node_modules/express/lib/router/index.js:346:12)
    at next (client/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (client/node_modules/express/lib/router/index.js:175:3)
    at Function.handle (client/node_modules/express/lib/application.js:181:10)
    at Server.app (client/node_modules/express/lib/express.js:39:9)
    at Server.emit (node:events:519:28)
    at parserOnIncoming (node:_http_server:1140:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)

Node.js v20.17.0